import frappe
from frappe.desk.query_report import get_chart

def execute(filters=None):
    filters = filters or {}

    # Query to get the relevant data
    tickets = frappe.get_all('Airplane Ticket', fields=['flight', 'total_amount'], filters=filters)
    
    # Debugging: Print ticket data to check if it's being fetched correctly
    print(tickets)

    # Prepare a dictionary to store revenue by airline prefix
    revenue_by_airline_prefix = {}

    for ticket in tickets:
        # Extract the airline prefix (before the first hyphen '-')
        airline_prefix = ticket['flight'].split('-')[0]
        revenue = ticket['total_amount']
        
        # Debugging: Print the extracted airline prefix and revenue
        print(f"Airline Prefix: {airline_prefix}, Revenue: {revenue}")

        if airline_prefix not in revenue_by_airline_prefix:
            revenue_by_airline_prefix[airline_prefix] = 0
        
        revenue_by_airline_prefix[airline_prefix] += revenue
    
    # Prepare columns for the report
    columns = [
        {"label": "Airline", "fieldname": "airline", "fieldtype": "Data", "width": 300},
        {"label": "Revenue", "fieldname": "revenue", "fieldtype": "Currency", "width": 200}
    ]

    # Prepare rows for the report, ensuring the format is correct for unpacking
    rows = []
    for airline_prefix, revenue in revenue_by_airline_prefix.items():
        rows.append([airline_prefix, revenue])  # Simple list with two items (airline, revenue)

    # Add a total row
    total_revenue = sum(revenue_by_airline_prefix.values())
    rows.append(['Total', total_revenue])  # Adding the total row

    # Debugging: Print the rows to verify the structure
    print("Formatted Rows for Linking:", rows)

    # Prepare chart data (Donut chart)
    chart_data = {
        'labels': list(revenue_by_airline_prefix.keys()),  # Properly get the keys (airline prefixes)
        'datasets': [{
            'name': 'Revenue',
            'values': list(revenue_by_airline_prefix.values())  # Properly get the values (revenues)
        }]
    }

    # Create the chart using get_chart
    chart = get_chart(
        chart_type="donut",  # Donut chart type
        chart_data=chart_data,  # The data to be used in the chart
        height=250,  # Height of the chart
        title="Revenue by Airline"  # Title of the chart
    )

    # Return the columns, rows, and chart data
    return {
        "columns": columns,
        "rows": rows,
        "chart": chart  # Chart generated by get_chart
    }
